name: deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install and configure Poetry
        run: |
          pip install -U pip poetry
          poetry config virtualenvs.create false
      - name: Install deps
        run: poetry install
      - name: Build en
        run: cd docs/en && mkdocs build
      - name: Build zh
        run: cd docs/zh && mkdocs build
      - name: Minio Deploy en
        uses: mamal72/minio-perfect-deploy-action@main
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "website"
          source_dir: "docs/en/site"
          target_dir: "/fastapi-admin-docs"
      - name: Minio Deploy zh
        uses: mamal72/minio-perfect-deploy-action@main
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: "website"
          source_dir: "docs/zh/site"
          target_dir: "/fastapi-admin-docs/zh"
