name: gh-pages
on: [ push, pull_request ]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install and configure Poetry
        run: |
          pip install -U pip poetry
          poetry config virtualenvs.create false
      - name: Install deps
        run: poetry install
      - name: Build en
        run: cd docs/en && mkdocs build
      - name: Deploy en
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/en/site
          cname: fastapi-admin-docs.long2ice.io
      - name: Build zh
        run: cd docs/zh && mkdocs build
      - name: Deploy zh
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/zh/site
          destination_dir: zh
          cname: fastapi-admin-docs.long2ice.io
